#!/usr/bin/env sh
# Bootstrap Judge0 CE on a Linux VM for Codentra staging.
#
# Run ON THE VM (Ubuntu 22.04/24.04, 2+ vCPU, 4+ GB RAM):
#   git clone https://github.com/abhishekkumar1803/codentra.git
#   cd codentra/infra/judge0 && chmod +x deploy-staging.sh smoke-test.sh && ./deploy-staging.sh
#
set -eu

DIR="$(cd "$(dirname "$0")" && pwd)"
cd "$DIR"

echo "==> Codentra Judge0 staging deploy (cwd=$DIR)"

if [ "$(uname -s)" != "Linux" ]; then
  echo "ERROR: Judge0 workers require Linux (isolate sandbox). Use a cloud VM, not macOS."
  exit 1
fi

install_docker() {
  if command -v docker >/dev/null 2>&1; then
    echo "==> Docker already installed"
    return
  fi
  echo "==> Installing Docker..."
  curl -fsSL https://get.docker.com | sh
  if [ -n "${SUDO_USER:-}" ]; then
    usermod -aG docker "$SUDO_USER" || true
    echo "NOTE: Log out and back in so '$SUDO_USER' can run docker without sudo."
  fi
}

generate_secret() {
  if command -v openssl >/dev/null 2>&1; then
    openssl rand -hex 24
  else
    tr -dc 'a-zA-Z0-9' </dev/urandom | head -c 48
  fi
}

write_judge0_conf() {
  PG_PASS="$(generate_secret)"
  REDIS_PASS="$(generate_secret)"
  AUTH_TOKEN="$(generate_secret)"

  cat > judge0.conf <<EOF
################################################################################
# Judge0 CE — generated by deploy-staging.sh ($(date -u +%Y-%m-%dT%H:%MZ))
# Backup this file securely. Do not commit to git.
################################################################################

JUDGE0_TELEMETRY_ENABLE=false

REDIS_HOST=redis
REDIS_PORT=6379
REDIS_PASSWORD=$REDIS_PASS

POSTGRES_HOST=db
POSTGRES_PORT=5432
POSTGRES_DB=judge0
POSTGRES_USER=judge0
POSTGRES_PASSWORD=$PG_PASS

AUTHN_HEADER=X-Auth-Token
AUTHN_TOKEN=$AUTH_TOKEN
EOF

  echo "==> Created judge0.conf with random secrets"
}

install_docker

if [ -f judge0.conf ] && grep -q '^AUTHN_TOKEN=.\+' judge0.conf 2>/dev/null; then
  echo "==> judge0.conf already exists — reusing (delete file to regenerate secrets)"
else
  write_judge0_conf
fi

set -a
# shellcheck disable=SC1091
. ./judge0.conf
set +a

if [ -z "${AUTHN_TOKEN:-}" ]; then
  echo "ERROR: AUTHN_TOKEN is empty in judge0.conf — required for internet-facing Judge0"
  exit 1
fi

export POSTGRES_PASSWORD="${POSTGRES_PASSWORD:?}"
export REDIS_PASSWORD="${REDIS_PASSWORD:?}"

# Docker Compose reads .env for ${REDIS_PASSWORD} in redis service command
cat > .env <<EOF
REDIS_PASSWORD=${REDIS_PASSWORD}
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
POSTGRES_DB=${POSTGRES_DB:-judge0}
POSTGRES_USER=${POSTGRES_USER:-judge0}
EOF
chmod 600 .env

echo "==> Pulling Docker images (first run may take 10–15 min)..."
if ! docker compose pull; then
  echo ""
  echo "WARN: Docker pull failed. If 'unauthorized', run: docker login"
  echo "      Then re-run: ./deploy-staging.sh"
  exit 1
fi

echo "==> Starting Judge0 stack..."
docker compose up -d

echo "==> Waiting for Judge0 API..."
ok=0
i=0
while [ "$i" -lt 90 ]; do
  if curl -sf -H "X-Auth-Token: $AUTHN_TOKEN" "http://127.0.0.1:2358/about" >/dev/null 2>&1; then
    ok=1
    break
  fi
  i=$((i + 1))
  sleep 2
done

if [ "$ok" -eq 0 ]; then
  echo "ERROR: Judge0 did not respond on :2358 within 3 minutes"
  docker compose ps
  docker compose logs server workers | tail -40
  exit 1
fi

echo "==> Running smoke test..."
chmod +x smoke-test.sh
./smoke-test.sh "http://127.0.0.1:2358" "$AUTHN_TOKEN"

PUBLIC_IP="$(curl -sf ifconfig.me 2>/dev/null || curl -sf icanhazip.com 2>/dev/null || true)"

echo ""
echo "=========================================="
echo "  Judge0 staging is ready"
echo "=========================================="
echo ""
echo "Local:  http://127.0.0.1:2358/about"
if [ -n "$PUBLIC_IP" ]; then
  echo "Public: http://${PUBLIC_IP}:2358/about"
fi
echo ""
echo "Open firewall on the VM + cloud security group:"
echo "  ufw allow 22/tcp"
echo "  ufw allow 2358/tcp"
echo ""
echo "Copy these to Railway → API service → Variables:"
echo ""
echo "  JUDGE_PROVIDER=judge0"
if [ -n "$PUBLIC_IP" ]; then
  echo "  JUDGE0_API_URL=http://${PUBLIC_IP}:2358"
else
  echo "  JUDGE0_API_URL=http://YOUR_VM_PUBLIC_IP:2358"
fi
echo "  JUDGE0_API_KEY=${AUTHN_TOKEN}"
echo ""
echo "Backup judge0.conf — it contains DB passwords and AUTHN_TOKEN."
echo "Full guide: docs/JUDGE0_STAGING_SETUP.md"
echo "=========================================="
